development:
  adapter: postgresql
  encoding: utf8
  database: orders_dev
  username: gopikrishnanayini
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: orders_test
  username: gopikrishnanayini
  password:
  host: localhost